// Generated by https://quicktype.io

export interface Dependent {
    name?:            string;
    lastname?:        string;
    email?:           string;
    phone?:           string;
    gender_id?:       string;
    birth?:           string;
    user_id?:         string;
    relationship_id?: string;
    status?:          boolean;
}

